// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleUserMembershipInitParameters struct {

	// (String, Deprecated) deprecated User group to add to the sudo rule
	// **deprecated** User group to add to the sudo rule
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (List of String) List of user groups to add to the sudo rule
	// List of user groups to add to the sudo rule
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule user membership resources on the same sudo rule. Manadatory for using users/groups configurations.
	// Unique identifier to differentiate multiple sudo rule user membership resources on the same sudo rule. Manadatory for using users/groups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated User to add to the sudo rule
	// **deprecated** User to add to the sudo rule
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (List of String) List of users to add to the sudo rule
	// List of users to add to the sudo rule
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type RuleUserMembershipObservation struct {

	// (String, Deprecated) deprecated User group to add to the sudo rule
	// **deprecated** User group to add to the sudo rule
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (List of String) List of user groups to add to the sudo rule
	// List of user groups to add to the sudo rule
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule user membership resources on the same sudo rule. Manadatory for using users/groups configurations.
	// Unique identifier to differentiate multiple sudo rule user membership resources on the same sudo rule. Manadatory for using users/groups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated User to add to the sudo rule
	// **deprecated** User to add to the sudo rule
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (List of String) List of users to add to the sudo rule
	// List of users to add to the sudo rule
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type RuleUserMembershipParameters struct {

	// (String, Deprecated) deprecated User group to add to the sudo rule
	// **deprecated** User group to add to the sudo rule
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (List of String) List of user groups to add to the sudo rule
	// List of user groups to add to the sudo rule
	// +kubebuilder:validation:Optional
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule user membership resources on the same sudo rule. Manadatory for using users/groups configurations.
	// Unique identifier to differentiate multiple sudo rule user membership resources on the same sudo rule. Manadatory for using users/groups configurations.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated User to add to the sudo rule
	// **deprecated** User to add to the sudo rule
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (List of String) List of users to add to the sudo rule
	// List of users to add to the sudo rule
	// +kubebuilder:validation:Optional
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

// RuleUserMembershipSpec defines the desired state of RuleUserMembership
type RuleUserMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleUserMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleUserMembershipInitParameters `json:"initProvider,omitempty"`
}

// RuleUserMembershipStatus defines the observed state of RuleUserMembership.
type RuleUserMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleUserMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RuleUserMembership is the Schema for the RuleUserMemberships API. FreeIPA Sudo rule user membership resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type RuleUserMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RuleUserMembershipSpec   `json:"spec"`
	Status RuleUserMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleUserMembershipList contains a list of RuleUserMemberships
type RuleUserMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleUserMembership `json:"items"`
}

// Repository type metadata.
var (
	RuleUserMembership_Kind             = "RuleUserMembership"
	RuleUserMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RuleUserMembership_Kind}.String()
	RuleUserMembership_KindAPIVersion   = RuleUserMembership_Kind + "." + CRDGroupVersion.String()
	RuleUserMembership_GroupVersionKind = CRDGroupVersion.WithKind(RuleUserMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&RuleUserMembership{}, &RuleUserMembershipList{})
}
