// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleHostMembershipInitParameters struct {

	// (String, Deprecated) deprecated Host to add to the sudo rule
	// **deprecated** Host to add to the sudo rule
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String, Deprecated) deprecated Hostgroup to add to the sudo rule
	// **deprecated** Hostgroup to add to the sudo rule
	Hostgroup *string `json:"hostgroup,omitempty" tf:"hostgroup,omitempty"`

	// (List of String) List of hostgroups to add to the sudo rule
	// List of hostgroups to add to the sudo rule
	Hostgroups []*string `json:"hostgroups,omitempty" tf:"hostgroups,omitempty"`

	// (List of String) List of hosts to add to the sudo rule
	// List of hosts to add to the sudo rule
	Hosts []*string `json:"hosts,omitempty" tf:"hosts,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule host membership resources on the same sudo rule. Manadatory for using hosts/hostgroups configurations.
	// Unique identifier to differentiate multiple sudo rule host membership resources on the same sudo rule. Manadatory for using hosts/hostgroups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RuleHostMembershipObservation struct {

	// (String, Deprecated) deprecated Host to add to the sudo rule
	// **deprecated** Host to add to the sudo rule
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String, Deprecated) deprecated Hostgroup to add to the sudo rule
	// **deprecated** Hostgroup to add to the sudo rule
	Hostgroup *string `json:"hostgroup,omitempty" tf:"hostgroup,omitempty"`

	// (List of String) List of hostgroups to add to the sudo rule
	// List of hostgroups to add to the sudo rule
	Hostgroups []*string `json:"hostgroups,omitempty" tf:"hostgroups,omitempty"`

	// (List of String) List of hosts to add to the sudo rule
	// List of hosts to add to the sudo rule
	Hosts []*string `json:"hosts,omitempty" tf:"hosts,omitempty"`

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule host membership resources on the same sudo rule. Manadatory for using hosts/hostgroups configurations.
	// Unique identifier to differentiate multiple sudo rule host membership resources on the same sudo rule. Manadatory for using hosts/hostgroups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type RuleHostMembershipParameters struct {

	// (String, Deprecated) deprecated Host to add to the sudo rule
	// **deprecated** Host to add to the sudo rule
	// +kubebuilder:validation:Optional
	Host *string `json:"host,omitempty" tf:"host,omitempty"`

	// (String, Deprecated) deprecated Hostgroup to add to the sudo rule
	// **deprecated** Hostgroup to add to the sudo rule
	// +kubebuilder:validation:Optional
	Hostgroup *string `json:"hostgroup,omitempty" tf:"hostgroup,omitempty"`

	// (List of String) List of hostgroups to add to the sudo rule
	// List of hostgroups to add to the sudo rule
	// +kubebuilder:validation:Optional
	Hostgroups []*string `json:"hostgroups,omitempty" tf:"hostgroups,omitempty"`

	// (List of String) List of hosts to add to the sudo rule
	// List of hosts to add to the sudo rule
	// +kubebuilder:validation:Optional
	Hosts []*string `json:"hosts,omitempty" tf:"hosts,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule host membership resources on the same sudo rule. Manadatory for using hosts/hostgroups configurations.
	// Unique identifier to differentiate multiple sudo rule host membership resources on the same sudo rule. Manadatory for using hosts/hostgroups configurations.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// RuleHostMembershipSpec defines the desired state of RuleHostMembership
type RuleHostMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleHostMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleHostMembershipInitParameters `json:"initProvider,omitempty"`
}

// RuleHostMembershipStatus defines the observed state of RuleHostMembership.
type RuleHostMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleHostMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RuleHostMembership is the Schema for the RuleHostMemberships API. FreeIPA Sudo rule host membership resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type RuleHostMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RuleHostMembershipSpec   `json:"spec"`
	Status RuleHostMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleHostMembershipList contains a list of RuleHostMemberships
type RuleHostMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleHostMembership `json:"items"`
}

// Repository type metadata.
var (
	RuleHostMembership_Kind             = "RuleHostMembership"
	RuleHostMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RuleHostMembership_Kind}.String()
	RuleHostMembership_KindAPIVersion   = RuleHostMembership_Kind + "." + CRDGroupVersion.String()
	RuleHostMembership_GroupVersionKind = CRDGroupVersion.WithKind(RuleHostMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&RuleHostMembership{}, &RuleHostMembershipList{})
}
