// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyServiceMembershipInitParameters struct {

	// (String) Unique identifier to differentiate multiple HBAC policy service membership resources on the same HBAC policy. Manadatory for using services/servicegroups configurations.
	// Unique identifier to differentiate multiple HBAC policy service membership resources on the same HBAC policy. Manadatory for using services/servicegroups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) HBAC policy name
	// HBAC policy name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated Service name the policy is applied t
	// **deprecated** Service name the policy is applied t
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// (String, Deprecated) deprecated Service group name the policy is applied to
	// **deprecated** Service group name the policy is applied to
	Servicegroup *string `json:"servicegroup,omitempty" tf:"servicegroup,omitempty"`

	// (List of String) List of service group name the policy is applied to
	// List of service group name the policy is applied to
	Servicegroups []*string `json:"servicegroups,omitempty" tf:"servicegroups,omitempty"`

	// (List of String) List of service name the policy is applied t
	// List of service name the policy is applied t
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`
}

type PolicyServiceMembershipObservation struct {

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier to differentiate multiple HBAC policy service membership resources on the same HBAC policy. Manadatory for using services/servicegroups configurations.
	// Unique identifier to differentiate multiple HBAC policy service membership resources on the same HBAC policy. Manadatory for using services/servicegroups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) HBAC policy name
	// HBAC policy name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated Service name the policy is applied t
	// **deprecated** Service name the policy is applied t
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// (String, Deprecated) deprecated Service group name the policy is applied to
	// **deprecated** Service group name the policy is applied to
	Servicegroup *string `json:"servicegroup,omitempty" tf:"servicegroup,omitempty"`

	// (List of String) List of service group name the policy is applied to
	// List of service group name the policy is applied to
	Servicegroups []*string `json:"servicegroups,omitempty" tf:"servicegroups,omitempty"`

	// (List of String) List of service name the policy is applied t
	// List of service name the policy is applied t
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`
}

type PolicyServiceMembershipParameters struct {

	// (String) Unique identifier to differentiate multiple HBAC policy service membership resources on the same HBAC policy. Manadatory for using services/servicegroups configurations.
	// Unique identifier to differentiate multiple HBAC policy service membership resources on the same HBAC policy. Manadatory for using services/servicegroups configurations.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) HBAC policy name
	// HBAC policy name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated Service name the policy is applied t
	// **deprecated** Service name the policy is applied t
	// +kubebuilder:validation:Optional
	Service *string `json:"service,omitempty" tf:"service,omitempty"`

	// (String, Deprecated) deprecated Service group name the policy is applied to
	// **deprecated** Service group name the policy is applied to
	// +kubebuilder:validation:Optional
	Servicegroup *string `json:"servicegroup,omitempty" tf:"servicegroup,omitempty"`

	// (List of String) List of service group name the policy is applied to
	// List of service group name the policy is applied to
	// +kubebuilder:validation:Optional
	Servicegroups []*string `json:"servicegroups,omitempty" tf:"servicegroups,omitempty"`

	// (List of String) List of service name the policy is applied t
	// List of service name the policy is applied t
	// +kubebuilder:validation:Optional
	Services []*string `json:"services,omitempty" tf:"services,omitempty"`
}

// PolicyServiceMembershipSpec defines the desired state of PolicyServiceMembership
type PolicyServiceMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyServiceMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyServiceMembershipInitParameters `json:"initProvider,omitempty"`
}

// PolicyServiceMembershipStatus defines the observed state of PolicyServiceMembership.
type PolicyServiceMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyServiceMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyServiceMembership is the Schema for the PolicyServiceMemberships API. FreeIPA HBAC policy service membership resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type PolicyServiceMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PolicyServiceMembershipSpec   `json:"spec"`
	Status PolicyServiceMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyServiceMembershipList contains a list of PolicyServiceMemberships
type PolicyServiceMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyServiceMembership `json:"items"`
}

// Repository type metadata.
var (
	PolicyServiceMembership_Kind             = "PolicyServiceMembership"
	PolicyServiceMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyServiceMembership_Kind}.String()
	PolicyServiceMembership_KindAPIVersion   = PolicyServiceMembership_Kind + "." + CRDGroupVersion.String()
	PolicyServiceMembership_GroupVersionKind = CRDGroupVersion.WithKind(PolicyServiceMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyServiceMembership{}, &PolicyServiceMembershipList{})
}
