// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type CmdInitParameters struct {

	// (String) Sudo command description
	// Sudo command description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Absolute path of the sudo command
	// Absolute path of the sudo command
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CmdObservation struct {

	// (String) Sudo command description
	// Sudo command description
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Absolute path of the sudo command
	// Absolute path of the sudo command
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CmdParameters struct {

	// (String) Sudo command description
	// Sudo command description
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Absolute path of the sudo command
	// Absolute path of the sudo command
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// CmdSpec defines the desired state of Cmd
type CmdSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CmdParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CmdInitParameters `json:"initProvider,omitempty"`
}

// CmdStatus defines the observed state of Cmd.
type CmdStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CmdObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Cmd is the Schema for the Cmds API. FreeIPA Sudo command resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type Cmd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   CmdSpec   `json:"spec"`
	Status CmdStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CmdList contains a list of Cmds
type CmdList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Cmd `json:"items"`
}

// Repository type metadata.
var (
	Cmd_Kind             = "Cmd"
	Cmd_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Cmd_Kind}.String()
	Cmd_KindAPIVersion   = Cmd_Kind + "." + CRDGroupVersion.String()
	Cmd_GroupVersionKind = CRDGroupVersion.WithKind(Cmd_Kind)
)

func init() {
	SchemeBuilder.Register(&Cmd{}, &CmdList{})
}
