//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembership) DeepCopyInto(out *CmdgroupMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembership.
func (in *CmdgroupMembership) DeepCopy() *CmdgroupMembership {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CmdgroupMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembershipInitParameters) DeepCopyInto(out *CmdgroupMembershipInitParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembershipInitParameters.
func (in *CmdgroupMembershipInitParameters) DeepCopy() *CmdgroupMembershipInitParameters {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembershipInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembershipList) DeepCopyInto(out *CmdgroupMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CmdgroupMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembershipList.
func (in *CmdgroupMembershipList) DeepCopy() *CmdgroupMembershipList {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CmdgroupMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembershipObservation) DeepCopyInto(out *CmdgroupMembershipObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembershipObservation.
func (in *CmdgroupMembershipObservation) DeepCopy() *CmdgroupMembershipObservation {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembershipParameters) DeepCopyInto(out *CmdgroupMembershipParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembershipParameters.
func (in *CmdgroupMembershipParameters) DeepCopy() *CmdgroupMembershipParameters {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembershipSpec) DeepCopyInto(out *CmdgroupMembershipSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembershipSpec.
func (in *CmdgroupMembershipSpec) DeepCopy() *CmdgroupMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CmdgroupMembershipStatus) DeepCopyInto(out *CmdgroupMembershipStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CmdgroupMembershipStatus.
func (in *CmdgroupMembershipStatus) DeepCopy() *CmdgroupMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(CmdgroupMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
