apiVersion: group.pelotech/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: group/v1alpha1/group
  labels:
    testing.upbound.io/example-name: group-posix
  name: group-posix
spec:
  forProvider:
    description: Test group
    gidNumber: "12345789"
    name: test-group
