//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembership) DeepCopyInto(out *RuleRunasuserMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembership.
func (in *RuleRunasuserMembership) DeepCopy() *RuleRunasuserMembership {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleRunasuserMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembershipInitParameters) DeepCopyInto(out *RuleRunasuserMembershipInitParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Runasuser != nil {
		in, out := &in.Runasuser, &out.Runasuser
		*out = new(string)
		**out = **in
	}
	if in.Runasusers != nil {
		in, out := &in.Runasusers, &out.Runasusers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembershipInitParameters.
func (in *RuleRunasuserMembershipInitParameters) DeepCopy() *RuleRunasuserMembershipInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembershipInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembershipList) DeepCopyInto(out *RuleRunasuserMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuleRunasuserMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembershipList.
func (in *RuleRunasuserMembershipList) DeepCopy() *RuleRunasuserMembershipList {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleRunasuserMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembershipObservation) DeepCopyInto(out *RuleRunasuserMembershipObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Runasuser != nil {
		in, out := &in.Runasuser, &out.Runasuser
		*out = new(string)
		**out = **in
	}
	if in.Runasusers != nil {
		in, out := &in.Runasusers, &out.Runasusers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembershipObservation.
func (in *RuleRunasuserMembershipObservation) DeepCopy() *RuleRunasuserMembershipObservation {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembershipParameters) DeepCopyInto(out *RuleRunasuserMembershipParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Runasuser != nil {
		in, out := &in.Runasuser, &out.Runasuser
		*out = new(string)
		**out = **in
	}
	if in.Runasusers != nil {
		in, out := &in.Runasusers, &out.Runasusers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembershipParameters.
func (in *RuleRunasuserMembershipParameters) DeepCopy() *RuleRunasuserMembershipParameters {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembershipSpec) DeepCopyInto(out *RuleRunasuserMembershipSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembershipSpec.
func (in *RuleRunasuserMembershipSpec) DeepCopy() *RuleRunasuserMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasuserMembershipStatus) DeepCopyInto(out *RuleRunasuserMembershipStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasuserMembershipStatus.
func (in *RuleRunasuserMembershipStatus) DeepCopy() *RuleRunasuserMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(RuleRunasuserMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
