// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleOptionInitParameters struct {

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Sudo option to add to the sudo rule.
	// Sudo option to add to the sudo rule.
	Option *string `json:"option,omitempty" tf:"option,omitempty"`
}

type RuleOptionObservation struct {

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Sudo option to add to the sudo rule.
	// Sudo option to add to the sudo rule.
	Option *string `json:"option,omitempty" tf:"option,omitempty"`
}

type RuleOptionParameters struct {

	// (String) Sudo rule name
	// Sudo rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Sudo option to add to the sudo rule.
	// Sudo option to add to the sudo rule.
	// +kubebuilder:validation:Optional
	Option *string `json:"option,omitempty" tf:"option,omitempty"`
}

// RuleOptionSpec defines the desired state of RuleOption
type RuleOptionSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleOptionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleOptionInitParameters `json:"initProvider,omitempty"`
}

// RuleOptionStatus defines the observed state of RuleOption.
type RuleOptionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleOptionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RuleOption is the Schema for the RuleOptions API. FreeIPA Sudo rule option resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type RuleOption struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.option) || (has(self.initProvider) && has(self.initProvider.option))",message="spec.forProvider.option is a required parameter"
	Spec   RuleOptionSpec   `json:"spec"`
	Status RuleOptionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleOptionList contains a list of RuleOptions
type RuleOptionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleOption `json:"items"`
}

// Repository type metadata.
var (
	RuleOption_Kind             = "RuleOption"
	RuleOption_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RuleOption_Kind}.String()
	RuleOption_KindAPIVersion   = RuleOption_Kind + "." + CRDGroupVersion.String()
	RuleOption_GroupVersionKind = CRDGroupVersion.WithKind(RuleOption_Kind)
)

func init() {
	SchemeBuilder.Register(&RuleOption{}, &RuleOptionList{})
}
