//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembership) DeepCopyInto(out *RuleDenycmdMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembership.
func (in *RuleDenycmdMembership) DeepCopy() *RuleDenycmdMembership {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleDenycmdMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembershipInitParameters) DeepCopyInto(out *RuleDenycmdMembershipInitParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroup != nil {
		in, out := &in.SudocmdGroup, &out.SudocmdGroup
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroups != nil {
		in, out := &in.SudocmdGroups, &out.SudocmdGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembershipInitParameters.
func (in *RuleDenycmdMembershipInitParameters) DeepCopy() *RuleDenycmdMembershipInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembershipInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembershipList) DeepCopyInto(out *RuleDenycmdMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuleDenycmdMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembershipList.
func (in *RuleDenycmdMembershipList) DeepCopy() *RuleDenycmdMembershipList {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleDenycmdMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembershipObservation) DeepCopyInto(out *RuleDenycmdMembershipObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroup != nil {
		in, out := &in.SudocmdGroup, &out.SudocmdGroup
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroups != nil {
		in, out := &in.SudocmdGroups, &out.SudocmdGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembershipObservation.
func (in *RuleDenycmdMembershipObservation) DeepCopy() *RuleDenycmdMembershipObservation {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembershipParameters) DeepCopyInto(out *RuleDenycmdMembershipParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroup != nil {
		in, out := &in.SudocmdGroup, &out.SudocmdGroup
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroups != nil {
		in, out := &in.SudocmdGroups, &out.SudocmdGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembershipParameters.
func (in *RuleDenycmdMembershipParameters) DeepCopy() *RuleDenycmdMembershipParameters {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembershipSpec) DeepCopyInto(out *RuleDenycmdMembershipSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembershipSpec.
func (in *RuleDenycmdMembershipSpec) DeepCopy() *RuleDenycmdMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleDenycmdMembershipStatus) DeepCopyInto(out *RuleDenycmdMembershipStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleDenycmdMembershipStatus.
func (in *RuleDenycmdMembershipStatus) DeepCopy() *RuleDenycmdMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(RuleDenycmdMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
