//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembership) DeepCopyInto(out *RuleRunasgroupMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembership.
func (in *RuleRunasgroupMembership) DeepCopy() *RuleRunasgroupMembership {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleRunasgroupMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembershipInitParameters) DeepCopyInto(out *RuleRunasgroupMembershipInitParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Runasgroup != nil {
		in, out := &in.Runasgroup, &out.Runasgroup
		*out = new(string)
		**out = **in
	}
	if in.Runasgroups != nil {
		in, out := &in.Runasgroups, &out.Runasgroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembershipInitParameters.
func (in *RuleRunasgroupMembershipInitParameters) DeepCopy() *RuleRunasgroupMembershipInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembershipInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembershipList) DeepCopyInto(out *RuleRunasgroupMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuleRunasgroupMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembershipList.
func (in *RuleRunasgroupMembershipList) DeepCopy() *RuleRunasgroupMembershipList {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleRunasgroupMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembershipObservation) DeepCopyInto(out *RuleRunasgroupMembershipObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Runasgroup != nil {
		in, out := &in.Runasgroup, &out.Runasgroup
		*out = new(string)
		**out = **in
	}
	if in.Runasgroups != nil {
		in, out := &in.Runasgroups, &out.Runasgroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembershipObservation.
func (in *RuleRunasgroupMembershipObservation) DeepCopy() *RuleRunasgroupMembershipObservation {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembershipParameters) DeepCopyInto(out *RuleRunasgroupMembershipParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Runasgroup != nil {
		in, out := &in.Runasgroup, &out.Runasgroup
		*out = new(string)
		**out = **in
	}
	if in.Runasgroups != nil {
		in, out := &in.Runasgroups, &out.Runasgroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembershipParameters.
func (in *RuleRunasgroupMembershipParameters) DeepCopy() *RuleRunasgroupMembershipParameters {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembershipSpec) DeepCopyInto(out *RuleRunasgroupMembershipSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembershipSpec.
func (in *RuleRunasgroupMembershipSpec) DeepCopy() *RuleRunasgroupMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleRunasgroupMembershipStatus) DeepCopyInto(out *RuleRunasgroupMembershipStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleRunasgroupMembershipStatus.
func (in *RuleRunasgroupMembershipStatus) DeepCopy() *RuleRunasgroupMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(RuleRunasgroupMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
