// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type GroupMembershipInitParameters struct {

	// (String, Deprecated) deprecated External member to add. name must refer to an external group. (Requires a valid AD Trust configuration).. Will be replaced by external_members.
	// **deprecated** External member to add. name must refer to an external group. (Requires a valid AD Trust configuration).. Will be replaced by external_members.
	ExternalMember *string `json:"externalMember,omitempty" tf:"external_member,omitempty"`

	// (List of String) External members to add as group members. name must refer to an external group. (Requires a valid AD Trust configuration).
	// External members to add as group members. name must refer to an external group. (Requires a valid AD Trust configuration).
	ExternalMembers []*string `json:"externalMembers,omitempty" tf:"external_members,omitempty"`

	// (String, Deprecated) deprecated User group to add. Will be replaced by groups.
	// **deprecated** User group to add. Will be replaced by groups.
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (List of String) User groups to add as group members
	// User groups to add as group members
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) Unique identifier to differentiate multiple user group membership resources on the same group. Manadatory for using users/groups/external_members configurations.
	// Unique identifier to differentiate multiple user group membership resources on the same group. Manadatory for using users/groups/external_members configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Group name
	// Group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated User to add. Will be replaced by users.
	// **deprecated** User to add. Will be replaced by users.
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (List of String) Users to add as group members
	// Users to add as group members
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type GroupMembershipObservation struct {

	// (String, Deprecated) deprecated External member to add. name must refer to an external group. (Requires a valid AD Trust configuration).. Will be replaced by external_members.
	// **deprecated** External member to add. name must refer to an external group. (Requires a valid AD Trust configuration).. Will be replaced by external_members.
	ExternalMember *string `json:"externalMember,omitempty" tf:"external_member,omitempty"`

	// (List of String) External members to add as group members. name must refer to an external group. (Requires a valid AD Trust configuration).
	// External members to add as group members. name must refer to an external group. (Requires a valid AD Trust configuration).
	ExternalMembers []*string `json:"externalMembers,omitempty" tf:"external_members,omitempty"`

	// (String, Deprecated) deprecated User group to add. Will be replaced by groups.
	// **deprecated** User group to add. Will be replaced by groups.
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (List of String) User groups to add as group members
	// User groups to add as group members
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier to differentiate multiple user group membership resources on the same group. Manadatory for using users/groups/external_members configurations.
	// Unique identifier to differentiate multiple user group membership resources on the same group. Manadatory for using users/groups/external_members configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Group name
	// Group name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated User to add. Will be replaced by users.
	// **deprecated** User to add. Will be replaced by users.
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (List of String) Users to add as group members
	// Users to add as group members
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type GroupMembershipParameters struct {

	// (String, Deprecated) deprecated External member to add. name must refer to an external group. (Requires a valid AD Trust configuration).. Will be replaced by external_members.
	// **deprecated** External member to add. name must refer to an external group. (Requires a valid AD Trust configuration).. Will be replaced by external_members.
	// +kubebuilder:validation:Optional
	ExternalMember *string `json:"externalMember,omitempty" tf:"external_member,omitempty"`

	// (List of String) External members to add as group members. name must refer to an external group. (Requires a valid AD Trust configuration).
	// External members to add as group members. name must refer to an external group. (Requires a valid AD Trust configuration).
	// +kubebuilder:validation:Optional
	ExternalMembers []*string `json:"externalMembers,omitempty" tf:"external_members,omitempty"`

	// (String, Deprecated) deprecated User group to add. Will be replaced by groups.
	// **deprecated** User group to add. Will be replaced by groups.
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// (List of String) User groups to add as group members
	// User groups to add as group members
	// +kubebuilder:validation:Optional
	Groups []*string `json:"groups,omitempty" tf:"groups,omitempty"`

	// (String) Unique identifier to differentiate multiple user group membership resources on the same group. Manadatory for using users/groups/external_members configurations.
	// Unique identifier to differentiate multiple user group membership resources on the same group. Manadatory for using users/groups/external_members configurations.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Group name
	// Group name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated User to add. Will be replaced by users.
	// **deprecated** User to add. Will be replaced by users.
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// (List of String) Users to add as group members
	// Users to add as group members
	// +kubebuilder:validation:Optional
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

// GroupMembershipSpec defines the desired state of GroupMembership
type GroupMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     GroupMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider GroupMembershipInitParameters `json:"initProvider,omitempty"`
}

// GroupMembershipStatus defines the observed state of GroupMembership.
type GroupMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        GroupMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// GroupMembership is the Schema for the GroupMemberships API. FreeIPA User Group Membership resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type GroupMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   GroupMembershipSpec   `json:"spec"`
	Status GroupMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// GroupMembershipList contains a list of GroupMemberships
type GroupMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []GroupMembership `json:"items"`
}

// Repository type metadata.
var (
	GroupMembership_Kind             = "GroupMembership"
	GroupMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: GroupMembership_Kind}.String()
	GroupMembership_KindAPIVersion   = GroupMembership_Kind + "." + CRDGroupVersion.String()
	GroupMembership_GroupVersionKind = CRDGroupVersion.WithKind(GroupMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&GroupMembership{}, &GroupMembershipList{})
}
