//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembership) DeepCopyInto(out *RuleAllowcmdMembership) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembership.
func (in *RuleAllowcmdMembership) DeepCopy() *RuleAllowcmdMembership {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembership)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleAllowcmdMembership) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembershipInitParameters) DeepCopyInto(out *RuleAllowcmdMembershipInitParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroup != nil {
		in, out := &in.SudocmdGroup, &out.SudocmdGroup
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroups != nil {
		in, out := &in.SudocmdGroups, &out.SudocmdGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembershipInitParameters.
func (in *RuleAllowcmdMembershipInitParameters) DeepCopy() *RuleAllowcmdMembershipInitParameters {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembershipInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembershipList) DeepCopyInto(out *RuleAllowcmdMembershipList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RuleAllowcmdMembership, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembershipList.
func (in *RuleAllowcmdMembershipList) DeepCopy() *RuleAllowcmdMembershipList {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembershipList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RuleAllowcmdMembershipList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembershipObservation) DeepCopyInto(out *RuleAllowcmdMembershipObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroup != nil {
		in, out := &in.SudocmdGroup, &out.SudocmdGroup
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroups != nil {
		in, out := &in.SudocmdGroups, &out.SudocmdGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembershipObservation.
func (in *RuleAllowcmdMembershipObservation) DeepCopy() *RuleAllowcmdMembershipObservation {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembershipObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembershipParameters) DeepCopyInto(out *RuleAllowcmdMembershipParameters) {
	*out = *in
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Sudocmd != nil {
		in, out := &in.Sudocmd, &out.Sudocmd
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroup != nil {
		in, out := &in.SudocmdGroup, &out.SudocmdGroup
		*out = new(string)
		**out = **in
	}
	if in.SudocmdGroups != nil {
		in, out := &in.SudocmdGroups, &out.SudocmdGroups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Sudocmds != nil {
		in, out := &in.Sudocmds, &out.Sudocmds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembershipParameters.
func (in *RuleAllowcmdMembershipParameters) DeepCopy() *RuleAllowcmdMembershipParameters {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembershipParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembershipSpec) DeepCopyInto(out *RuleAllowcmdMembershipSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembershipSpec.
func (in *RuleAllowcmdMembershipSpec) DeepCopy() *RuleAllowcmdMembershipSpec {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembershipSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RuleAllowcmdMembershipStatus) DeepCopyInto(out *RuleAllowcmdMembershipStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RuleAllowcmdMembershipStatus.
func (in *RuleAllowcmdMembershipStatus) DeepCopy() *RuleAllowcmdMembershipStatus {
	if in == nil {
		return nil
	}
	out := new(RuleAllowcmdMembershipStatus)
	in.DeepCopyInto(out)
	return out
}
