// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleAllowcmdMembershipInitParameters struct {

	// (String) Unique identifier to differentiate multiple sudo rule denied membership resources on the same sudo rule. Manadatory for using sudocmds/sudocmd_groups configurations.
	// Unique identifier to differentiate multiple sudo rule denied membership resources on the same sudo rule. Manadatory for using sudocmds/sudocmd_groups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated Sudo command to allow by the sudo rule
	// **deprecated** Sudo command to allow by the sudo rule
	Sudocmd *string `json:"sudocmd,omitempty" tf:"sudocmd,omitempty"`

	// (String, Deprecated) deprecated Sudo command group to allow by the sudo rule
	// **deprecated** Sudo command group to allow by the sudo rule
	SudocmdGroup *string `json:"sudocmdGroup,omitempty" tf:"sudocmd_group,omitempty"`

	// (List of String) List of sudo command group to allow by the sudo rule
	// List of sudo command group to allow by the sudo rule
	SudocmdGroups []*string `json:"sudocmdGroups,omitempty" tf:"sudocmd_groups,omitempty"`

	// (List of String) List of Sudo command to allow by the sudo rule
	// List of Sudo command to allow by the sudo rule
	Sudocmds []*string `json:"sudocmds,omitempty" tf:"sudocmds,omitempty"`
}

type RuleAllowcmdMembershipObservation struct {

	// (String) ID of the resource
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Unique identifier to differentiate multiple sudo rule denied membership resources on the same sudo rule. Manadatory for using sudocmds/sudocmd_groups configurations.
	// Unique identifier to differentiate multiple sudo rule denied membership resources on the same sudo rule. Manadatory for using sudocmds/sudocmd_groups configurations.
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated Sudo command to allow by the sudo rule
	// **deprecated** Sudo command to allow by the sudo rule
	Sudocmd *string `json:"sudocmd,omitempty" tf:"sudocmd,omitempty"`

	// (String, Deprecated) deprecated Sudo command group to allow by the sudo rule
	// **deprecated** Sudo command group to allow by the sudo rule
	SudocmdGroup *string `json:"sudocmdGroup,omitempty" tf:"sudocmd_group,omitempty"`

	// (List of String) List of sudo command group to allow by the sudo rule
	// List of sudo command group to allow by the sudo rule
	SudocmdGroups []*string `json:"sudocmdGroups,omitempty" tf:"sudocmd_groups,omitempty"`

	// (List of String) List of Sudo command to allow by the sudo rule
	// List of Sudo command to allow by the sudo rule
	Sudocmds []*string `json:"sudocmds,omitempty" tf:"sudocmds,omitempty"`
}

type RuleAllowcmdMembershipParameters struct {

	// (String) Unique identifier to differentiate multiple sudo rule denied membership resources on the same sudo rule. Manadatory for using sudocmds/sudocmd_groups configurations.
	// Unique identifier to differentiate multiple sudo rule denied membership resources on the same sudo rule. Manadatory for using sudocmds/sudocmd_groups configurations.
	// +kubebuilder:validation:Optional
	Identifier *string `json:"identifier,omitempty" tf:"identifier,omitempty"`

	// (String) Sudo rule name
	// Sudo rule name
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String, Deprecated) deprecated Sudo command to allow by the sudo rule
	// **deprecated** Sudo command to allow by the sudo rule
	// +kubebuilder:validation:Optional
	Sudocmd *string `json:"sudocmd,omitempty" tf:"sudocmd,omitempty"`

	// (String, Deprecated) deprecated Sudo command group to allow by the sudo rule
	// **deprecated** Sudo command group to allow by the sudo rule
	// +kubebuilder:validation:Optional
	SudocmdGroup *string `json:"sudocmdGroup,omitempty" tf:"sudocmd_group,omitempty"`

	// (List of String) List of sudo command group to allow by the sudo rule
	// List of sudo command group to allow by the sudo rule
	// +kubebuilder:validation:Optional
	SudocmdGroups []*string `json:"sudocmdGroups,omitempty" tf:"sudocmd_groups,omitempty"`

	// (List of String) List of Sudo command to allow by the sudo rule
	// List of Sudo command to allow by the sudo rule
	// +kubebuilder:validation:Optional
	Sudocmds []*string `json:"sudocmds,omitempty" tf:"sudocmds,omitempty"`
}

// RuleAllowcmdMembershipSpec defines the desired state of RuleAllowcmdMembership
type RuleAllowcmdMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleAllowcmdMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleAllowcmdMembershipInitParameters `json:"initProvider,omitempty"`
}

// RuleAllowcmdMembershipStatus defines the observed state of RuleAllowcmdMembership.
type RuleAllowcmdMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleAllowcmdMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RuleAllowcmdMembership is the Schema for the RuleAllowcmdMemberships API. FreeIPA Sudo rule allow command membership resource
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,freeipa}
type RuleAllowcmdMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RuleAllowcmdMembershipSpec   `json:"spec"`
	Status RuleAllowcmdMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleAllowcmdMembershipList contains a list of RuleAllowcmdMemberships
type RuleAllowcmdMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RuleAllowcmdMembership `json:"items"`
}

// Repository type metadata.
var (
	RuleAllowcmdMembership_Kind             = "RuleAllowcmdMembership"
	RuleAllowcmdMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RuleAllowcmdMembership_Kind}.String()
	RuleAllowcmdMembership_KindAPIVersion   = RuleAllowcmdMembership_Kind + "." + CRDGroupVersion.String()
	RuleAllowcmdMembership_GroupVersionKind = CRDGroupVersion.WithKind(RuleAllowcmdMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&RuleAllowcmdMembership{}, &RuleAllowcmdMembershipList{})
}
