apiVersion: sudo_rule.pelotech/v1alpha1
kind: Rule
metadata:
  annotations:
    meta.upbound.io/example-id: sudo_rule/v1alpha1/rule
  labels:
    testing.upbound.io/example-name: sysadmins
  name: sysadmins
spec:
  forProvider:
    description: Sysadmins have all permissions
    name: sysadmins
